Expose authenticator, authorizer and add support for no authentication
bitnami/bitnami-docker-cassandra pull request #78
Opened 2020-09-08 07:34 UTC by blackheat

Description of the change
A new environment variable CASSANDRA_AUTHENTICATOR, CASSANDRA_AUTHORIZER is added to support defining authenticator and authorizer in Cassandra cluster.
Also, a new environment variable CASSANDRA_ALLOW_EMPTY_PASSWORD is added to support non password login. For development purposes only.

Benefits
Configuration setting "authenticator", "authorizer" are used to define which authenticator and/or authorizer to be used.
Also, environment variable CASSANDRA_ALLOW_EMPTY_PASSWORD will allow Cassandra to run with no authentication (for development purposes only) by setting "authenticator" and "authorizer" to "AllowAllAuthenticator" and "AllowAllAuthorizer".

2020-09-08 08:03 UTC, javsalgar requested changes
Thank you very much for the PR!

In other solutions we put a warning for the user when *_EMPTY_PASSWORD is set (for example in MariaDB). I think it would be nice to have it here as well. I also think that the AllowAllAuthorizer should be set when ALLOW_EMPTY_PASSWORD is set and CASSANDRA_PASSWORD is set to null, right?  At least that's what we do in other solutions, because the user may believe that the password is set but it actually isn't, and "allowing empty passwords" doesn't necessarily mean "set passwordless authentication". WYDT?

2020-09-09 09:13 UTC, blackheat commented
Hi,
Thanks for your suggestion. I totally agree with it. I've made changes to PR according to your suggestion.

2020-09-10 08:03 UTC, javsalgar requested changes

2020-09-10 08:03 UTC, javsalgar commented on 3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh
> +            export CASSANDRA_PASSWORD="cassandra"
Shouldn't this return the `empty_password_error` instead of changing the password value?

2020-09-10 08:14 UTC, blackheat commented on 3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh
> +            export CASSANDRA_PASSWORD="cassandra"
I saw that the default behavior of this image is to set the default password to "cassandra" if CASSANDRA_PASSWORD does not set. I think it's okay to retain this default behavior. What do you think ?

2020-09-10 08:23 UTC, javsalgar commented on 3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh
> +            export CASSANDRA_PASSWORD="cassandra"
It makes sense for backwads compatibility. However, now that we allow empty passwords, I would at least put a warning.

2020-09-14 03:26 UTC, blackheat commented on 3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh
> +            export CASSANDRA_PASSWORD="cassandra"
Hi javsalgar, I've updated PR according to your recommendations. Can you review it for me ? Thanks.

2020-09-16 03:17 UTC, blackheat commented
Hi javsalgar,
Thanks for your suggestion. I totally agree with it. I've made changes to PR according to your suggestion. Can you review it for me ? Thanks

2020-09-16 07:28 UTC, javsalgar approved these changes

2020-09-16 07:28 UTC, merged