Added Dynamic Snitch Override and Broke out commit log
bitnami/bitnami-docker-cassandra pull request #86
Opened 2021-01-24 00:44 UTC by jemantheiy

**Description of the change**
1.  Added a parameter to override dynamic snitch to optimize a cluster.  by default it's true but according to the last pickle, recommended to be false (disabled).

2.  Allow the ability to set commit log to a different partition.  Performance-wise you want your commit log and data log on two different partitions.

**Benefits**
Performance boost to Cassandra based on last pickle/DataStax best practices. 

**Possible drawbacks**
None, just able to control changes more.  

**Applicable issues**
Prior unable to set commit log and data log to separate partitions and to override dynamic snitch you have to supply a complete cassandra.yaml

**Additional information**

I use this docker image in docker swarm and Kubernetes setting (with Bitnami helm chart)

2021-01-25 11:42 UTC, FraPazGal requested changes
Hello @jemanthei,

Thanks for the PR! I added some comments, could you take a look?

2021-01-25 13:30 UTC, jemantheiy commented on 3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh
> +export CASSANDRA_DYNAMIC_SNITCH="${CASSANDRA_DYNAMIC_SNITCH:true}"
Good call and catch.  Thanks.  The docs that show dynamic_snitch are below.  

https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/architecture/archSnitchDynamic.html 
https://thelastpickle.com/blog/2019/01/30/new-cluster-recommendations.html
https://www.slideshare.net/JonHaddad/performance-tuning-86995333

2021-01-26 11:59 UTC, FraPazGal reviewed
Hi @jemantheiy,

I left some comments, as there are some issues with `dynamic_snitch`, please tell me your thoughts on it.

2021-01-26 11:59 UTC, FraPazGal commented on 3/debian-10/rootfs/opt/bitnami/scripts/cassandra/postunpack.sh
> +for dir in "$CASSANDRA_INITSCRIPTS_DIR" "$CASSANDRA_TMP_DIR" "$CASSANDRA_HISTORY_DIR" "$CASSANDRA_CONF_DIR" "$CASSANDRA_LOG_DIR" "$CASSANDRA_MOUNTED_CONF_DIR" "$CASSANDRA_VOLUME_DIR" "$CASSANDRA_COMM
I tested this and it seems that cassandra creates this directory so it isn't necessary to have `$CASSANDRA_COMMITLOG_DIR`, my bad.

2021-01-26 11:59 UTC, FraPazGal commented on 3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh
> +export CASSANDRA_COMMITLOG_DIR="{CASSANDRA_COMMITLOG_DIR:-${CASSANDRA_VOLUME_DIR}/data/commitlog}"
There is a `$` missing here:

```suggestion
export CASSANDRA_COMMITLOG_DIR="${CASSANDRA_COMMITLOG_DIR:-${CASSANDRA_VOLUME_DIR}/data/commitlog}"
```

2021-01-26 11:59 UTC, FraPazGal commented on 3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh
> +        cassandra_yaml_set "dynamic_snitch" "$CASSANDRA_DYNAMIC_SNITCH"
Having tested this, `dynamic_snitch=false` is not being set in the conf file. This is because `dynamic_snitch` is not present by default in the [conf file](https://raw.githubusercontent.com/apache/cassandra/trunk/conf/cassandra.yaml) (even as a comment) and so `cassandra_yaml_set()` is not doing anything. This function only calls [replace_in_file()](https://github.com/bitnami/bitnami-docker-cassandra/blob/c57a38c2237d77adecd45b9fef517eb53799aad2/3/debian-10/prebuildfs/opt/bitnami/scripts/libfile.sh#L17), which is basically a `sed` command.

For this to work, we would need to include a new line to the conf file, which would require a new function or at least expand `cassandra_yaml_set` to allow adding lines given an optional parameter.

It seems strange to me that `dynamic_snitch` is not well documented in the official documentation and the are few references to it. The best thing I found is a [cassandra's bug report ticket](https://issues.apache.org/jira/browse/CASSANDRA-6908?focusedCommentId=14803284&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14803284) talking about this that offers some workarounds. 

Another solution would be to use a [custom conf file](https://github.com/bitnami/bitnami-docker-cassandra#configuration-file), though it is true that having it as an env would be easier to customise. What do you think?

2021-01-26 11:59 UTC, FraPazGal commented on README.md
> + - `CASSANDRA_DYNAMIC_SNITCH`: Dynamic snitching property that enables Cassandra to identify most performance nodes to answer a query.  If left empty, this will be enabled (true).  If set to false, t
It may be nitpicking, but it looks like there are 2 whitespaces after ever `.`

2021-01-27 10:36 UTC, jemantheiy commented on 3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh
> +        cassandra_yaml_set "dynamic_snitch" "$CASSANDRA_DYNAMIC_SNITCH"
After thinking it over and looking at long term Cassandra (4) and the changes coming.  I think it's probably best to revert the dyanmic_snitch setting and simply focus on the ability to break out commit logs and data directory since it's recommended for best performance on spindle drives to have two different partitions.  (I'm on a bounded Kubernetes cluster that is on prem).  Thoughts?

2021-01-27 10:36 UTC, jemantheiy commented on 3/debian-10/rootfs/opt/bitnami/scripts/cassandra/postunpack.sh
> +for dir in "$CASSANDRA_INITSCRIPTS_DIR" "$CASSANDRA_TMP_DIR" "$CASSANDRA_HISTORY_DIR" "$CASSANDRA_CONF_DIR" "$CASSANDRA_LOG_DIR" "$CASSANDRA_MOUNTED_CONF_DIR" "$CASSANDRA_VOLUME_DIR" "$CASSANDRA_COMM
Probably still good to have for directness.  thanks.

2021-01-27 10:37 UTC, jemantheiy commented on README.md
> + - `CASSANDRA_DYNAMIC_SNITCH`: Dynamic snitching property that enables Cassandra to identify most performance nodes to answer a query.  If left empty, this will be enabled (true).  If set to false, t
Fixed, sorry double tapping space bar after a period .

2021-01-28 13:29 UTC, FraPazGal commented on 3/debian-10/rootfs/opt/bitnami/scripts/cassandra/postunpack.sh
> +for dir in "$CASSANDRA_INITSCRIPTS_DIR" "$CASSANDRA_TMP_DIR" "$CASSANDRA_HISTORY_DIR" "$CASSANDRA_CONF_DIR" "$CASSANDRA_LOG_DIR" "$CASSANDRA_MOUNTED_CONF_DIR" "$CASSANDRA_VOLUME_DIR" "$CASSANDRA_COMM
The issue is that if we create the dir here, it is created as root and cassandra needs to create the `/bitnami/cassandra/data/` directory with its daemon user or it would throw a permissions error otherwise.  

`cassandra_1  | ERROR [main] 2021-01-28 13:15:57,342 CassandraDaemon.java:803 - Has no permission to create directory /bitnami/cassandra/data/data`

We should move this check to `cassandra_initialize()`:

https://github.com/bitnami/bitnami-docker-cassandra/blob/311616c624e580beadcc2807481435089cef4ade/3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh#L711

2021-01-28 13:31 UTC, FraPazGal commented on 3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh
> +        cassandra_yaml_set "dynamic_snitch" "$CASSANDRA_DYNAMIC_SNITCH"
Yes, I think that may be a good compromise, as it is something that is being actively worked on for Cassandra 4 and there is still the possibility of working around this using your custom config file.

2021-02-01 17:41 UTC, jemantheiy commented on 3/debian-10/rootfs/opt/bitnami/scripts/libcassandra.sh
> +        cassandra_yaml_set "dynamic_snitch" "$CASSANDRA_DYNAMIC_SNITCH"
Great I reverted the changes.

2021-02-01 17:42 UTC, jemantheiy commented on 3/debian-10/rootfs/opt/bitnami/scripts/cassandra/postunpack.sh
> +for dir in "$CASSANDRA_INITSCRIPTS_DIR" "$CASSANDRA_TMP_DIR" "$CASSANDRA_HISTORY_DIR" "$CASSANDRA_CONF_DIR" "$CASSANDRA_LOG_DIR" "$CASSANDRA_MOUNTED_CONF_DIR" "$CASSANDRA_VOLUME_DIR" "$CASSANDRA_COMM
fixed and updated.

2021-02-04 17:48 UTC, andresbono approved these changes

2021-02-04 17:49 UTC, andresbono commented
Hi @jemantheiy, the PR should be now ready to be merged. We have done some minor changes on it.

2021-02-04 18:13 UTC, merged

2021-02-04 18:13 UTC, andresbono commented
It is now merged! 🎉 Thanks so much for your contribution!